version: '2'

catalog:
  name: Redis HA
  version: v1.0.0-rancher1

  questions:
    - variable: "redis_password"
      description: "A strong password for authentication of every client. Mind the Redis Security notes at https://redis.io/topics/security."
      label: "Redis password"
      required: true
      type: "password"

    - variable: "redis_sentinel_quorum"
      default: "2"
      description: "The number of Redis Sentinels that need to detect an error condition. More details about it at https://redis.io/topics/sentinel."
      label: "Redis Sentinel quorum number"
      required: true
      type: "int"

    - variable: "redis_sentinel_master_name"
      default: "redis-ha"
      description: "The name of the Redis instance group (master and slaves)."
      label: "Redis Sentinel master name"
      required: false
      type: "string"

    - variable: "global_mode"
      default: false
      description: "Would you like to deploy Redis instances on every hosts?"
      label: "Enable global mode?"
      required: true
      type: boolean

    - variable: "debug_mode"
      default: false
      description: "Would you like to get more details of instances entrypoint?"
      label: "Enable debug mode?"
      required: false
      type: boolean

services:
  redis:
    scale: 2

  sentinel:
    scale: ${redis_sentinel_quorum}